;; -*- lexical-binding: t; -*-
;; Realistic workflows used to check a pruned Emacs. Each prints OK/ERROR and
;; writes the list of Lisp files it loaded to $S/trace-NAME.txt.
;; Usage (see tools/verify-prune.sh):
;;   S=outdir R=repo-root emacs -Q --batch -l tools/workflows.el --eval '(run-workflow "name")'
;; Needs network for the package-* and url-https workflows.
(setq native-comp-jit-compilation nil byte-compile-warnings nil)
(defvar S (or (getenv "S") temporary-file-directory))
(defvar tmp (make-temp-file "wf" t))
(defun wf-package-refresh ()
  (require 'package)
  (setq package-user-dir (concat tmp "/pkgs") package-check-signature nil
        package-archives '(("nongnu" . "https://elpa.nongnu.org/nongnu/") ("gnu" . "https://elpa.gnu.org/packages/") ("melpa" . "https://melpa.org/packages/")))
  (package-refresh-contents)
  (unless (assq 'evil package-archive-contents) (error "no evil in archive")))
(defun wf-package-install ()
  (wf-package-refresh) (package-install 'evil)
  (unless (package-installed-p 'evil) (error "evil not installed")))
(defun wf-package-install-signed ()
  (require 'package)
  (setq package-user-dir (concat tmp "/pkgs2")
        package-archives '(("gnu" . "https://elpa.gnu.org/packages/")))
  (package-refresh-contents) (package-install 'rainbow-mode))
(defun wf-url-https ()
  (require 'url)
  (with-current-buffer (url-retrieve-synchronously "https://elpa.gnu.org/packages/archive-contents" t nil 30)
    (unless (> (buffer-size) 1000) (error "small response"))))
(defun wf-vc ()
  (require 'vc) (require 'vc-git)
  (let ((default-directory (concat (getenv "R") "/"))) (vc-git-root default-directory) (vc-state (concat (getenv "R") "/README.md")) (vc-git-working-revision (concat (getenv "R") "/README.md"))))
(defun wf-diff-ediff ()
  (require 'diff-mode) (require 'ediff) (require 'smerge-mode)
  (let ((a (concat tmp "/a")) (b (concat tmp "/b"))) (with-temp-file a (insert "x\n")) (with-temp-file b (insert "y\n"))
    (with-current-buffer (diff-no-select a b nil t) (diff-mode) (font-lock-ensure))))
(defun wf-dired-grep-find ()
  (require 'dired) (require 'dired-aux) (require 'grep) (require 'find-dired) (require 'find-cmd)
  (dired tmp) (find-cmd '(name "*.el"))
  (grep-compute-defaults))
(defun wf-help ()
  (require 'help-fns) (describe-function 'car) (describe-variable 'load-path) (describe-key (kbd "C-x C-f")) (apropos-command "org-")
  (require 'shortdoc) (shortdoc-display-group 'string) (require 'info) (Info-find-file "emacs"))
(defun wf-customize ()
  (require 'cus-edit) (require 'wid-edit) (custom-buffer-create (list (list 'fill-column 'custom-variable))))
(defun wf-calendar ()
  (require 'calendar) (require 'diary-lib) (require 'holidays) (require 'icalendar)
  (calendar-holiday-list) (require 'time-date))
(defun wf-tramp ()
  (require 'tramp) (ignore-errors (expand-file-name "/ssh:nobody@localhost:/tmp")) (tramp-dissect-file-name "/ssh:a@b:/c"))
(defun wf-compile-edebug-ert ()
  (require 'compile) (require 'edebug) (require 'ert) (require 'elp) (require 'profiler)
  (ert-deftest wf-t () (should t)) (ert-run-tests-batch "wf-t"))
(defun wf-compose-mail ()
  (require 'sendmail) (require 'message) (require 'emacsbug) (require 'rfc822) (require 'mail-utils) (require 'mailcap) (require 'smtpmail)
  (with-temp-buffer (message-mode) (insert "To: a@b\nSubject: t\n--text follows this line--\nhi") (message-fetch-field "to")))
(defun wf-eglot-project-xref ()
  (require 'eglot) (require 'project) (require 'xref) (require 'flymake) (require 'eldoc)
  (with-temp-buffer (emacs-lisp-mode) (insert "(defun f () 1)") (xref-find-backend) (flymake-mode 1) (eldoc-mode 1))
  (project-current nil (getenv "R")))
(defun wf-treesit-python-js ()
  (require 'treesit) (require 'python) (require 'js) (require 'c-ts-mode) (with-temp-buffer (python-mode) (insert "def f(): pass\n") (font-lock-ensure) (imenu--make-index-alist)))
(defun wf-misc-ui ()
  (require 'ibuffer) (require 'recentf) (require 'savehist) (require 'winner) (require 'which-key) (require 'tab-bar) (require 'bookmark) (require 'desktop) (require 'ido) (require 'icomplete) (require 'completion-preview)
  (require 'speedbar) (require 'imenu) (require 'whitespace) (require 'so-long) (require 'hideshow) (require 'outline) (require 'flyspell) (require 'ispell) (require 'doc-view) (require 'image-mode) (require 'shell) (require 'comint) (require 'eshell) (require 'esh-mode) (require 'term) (require 'calc) (require 'proced) (require 'man) (require 'woman) (require 'texinfo) (require 'sql) (require 'gdb-mi) (require 'server) (require 'dictionary) (require 'json) (require 'soap-client) (require 'zeroconf))
(defun run-workflow (name)
  (let ((fn (intern (concat "wf-" name))) (status "OK"))
    (condition-case e (funcall fn) (error (setq status (format "ERROR: %s" (error-message-string e)))))
    (with-temp-file (format "%s/trace-%s.txt" S name)
      (dolist (h load-history) (when (stringp (car h)) (insert (car h) "\n"))))
    (princ (format "%-26s %s\n" name status))))
(defun wf-shr ()
  (require 'shr) (require 'eww) (require 'url) (require 'browse-url) (require 'dom) (require 'xml)
  (with-temp-buffer (insert "<html><body><h1>Hi</h1><a href='x'>l</a><table><tr><td>1</td></tr></table></body></html>")
    (let ((dom (libxml-parse-html-region (point-min) (point-max)))) (erase-buffer) (shr-insert-document dom))))
